name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Fira Code
        run: |
          mkdir -p ~/.local/share/fonts
          cd /tmp

          wget https://github.com/tonsky/FiraCode/releases/download/6.2/Fira_Code_v6.2.zip
          unzip Fira_Code_v6.2.zip -d FiraCode

          cp FiraCode/ttf/*.ttf ~/.local/share/fonts/

          fc-cache -f -v
      
      - name: Set up Git repository
        uses: actions/checkout@v2  
        
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            cd src
            latexmk
            
      - name: Upload document
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: src/main.pdf
